### ISSUE TITLE
EditThatPreviousMaster seems to just be editing that next master

### ISSUE THREAD

**Issue by thundernixon** [LettError/editThatNextMasterRoboFontExtension#4]
I get the nearly same result whether I trigger the EditThatPreviousMaster or EditThatNextMaster. The only difference I'm finding is that if I have previously used EditThatNextMaster, running EditThatPreviousMaster goes to the first source of my designspace ... but then using EditThatPreviousMaster again just steps through them in the same direction as before.

I'm using it with Skateboard, from a clone of the latest version on GitHub (05e8387).

**Comment by LettError** [comment]
Do you have more or all masters open?

**Comment by thundernixon** [comment]
I have four masters in a designspace, and all four open. They are:

- Light (Recursive Mono-Casual A.ufo​)
- Light Italic (Recursive Mono-Casual A Italic - gradually fixed.ufo​)
- ExtraBold (Recursive Mono-Casual B.ufo​)
- ExtraBold Italic (Recursive Mono-Casual B Italic - gradually fixed.ufo​)

I can invite you into the (currently private) repo, if that would be helpful as a test case.

**Comment by LettError** [comment]
Sure

**Comment by thundernixon** [comment]
Fixed by a18f7eeb!

Stoked to have full use of this simple but extremely useful tool again. Thanks so much for finding and fixing the bug, Erik!
